#!/usr/bin/env python3
"""
Generate a C header mapping trainer IDs to region map section IDs.

Parses data/maps/*/map.json for region_map_section and
data/maps/*/scripts.inc for trainerbattle_* commands to build
a compile-time lookup table.

Outputs a flat positional array (no designated initializers) for
maximum compatibility with AGBCC.
"""

import json
import os
import re
import sys

BASE_DIR = os.path.join(os.path.dirname(__file__), '..')
MAPS_DIR = os.path.join(BASE_DIR, 'data', 'maps')
OPPONENTS_H = os.path.join(BASE_DIR, 'include', 'constants', 'opponents.h')
REGION_MAP_H = os.path.join(BASE_DIR, 'include', 'constants', 'region_map_sections.h')
OUTPUT_FILE = os.path.join(BASE_DIR, 'src', 'data', 'battle_royale', 'trainer_map_sections.h')

TRAINERBATTLE_RE = re.compile(r'trainerbattle_\w+\s+(TRAINER_\w+)')
DEFINE_RE = re.compile(r'#define\s+(TRAINER\w+)\s+(\d+)')


def parse_trainer_ids(path):
    """Parse opponents.h to get TRAINER_* -> numeric ID mapping and TRAINERS_COUNT."""
    trainer_ids = {}
    trainers_count = 0
    with open(path, 'r') as f:
        for line in f:
            m = DEFINE_RE.match(line.strip())
            if m:
                name, val = m.group(1), int(m.group(2))
                trainer_ids[name] = val
    trainers_count = trainer_ids.get('TRAINERS_COUNT', 0)
    return trainer_ids, trainers_count


def parse_mapsec_enum(path):
    """Parse region_map_sections.h to get MAPSEC_* -> numeric value mapping."""
    mapsecs = {}
    in_enum = False
    counter = 0
    with open(path, 'r') as f:
        for line in f:
            stripped = line.strip().rstrip(',')
            if 'enum {' in line or 'enum{' in line:
                in_enum = True
                counter = 0
                continue
            if in_enum:
                if stripped == '};':
                    break
                if stripped.startswith('//') or stripped == '':
                    continue
                if '=' in stripped:
                    parts = stripped.split('=')
                    name = parts[0].strip()
                    val = int(parts[1].strip())
                    mapsecs[name] = val
                    counter = val + 1
                else:
                    mapsecs[stripped] = counter
                    counter += 1
    return mapsecs


def main():
    output_path = sys.argv[1] if len(sys.argv) > 1 else OUTPUT_FILE

    trainer_ids, trainers_count = parse_trainer_ids(OPPONENTS_H)
    mapsec_values = parse_mapsec_enum(REGION_MAP_H)
    mapsec_none = mapsec_values.get('MAPSEC_NONE', 222)

    # Build trainer name -> mapsec string mapping from map scripts
    trainer_to_mapsec = {}

    for map_name in sorted(os.listdir(MAPS_DIR)):
        map_dir = os.path.join(MAPS_DIR, map_name)
        map_json_path = os.path.join(map_dir, 'map.json')
        scripts_inc = os.path.join(map_dir, 'scripts.inc')

        if not os.path.isfile(map_json_path) or not os.path.isfile(scripts_inc):
            continue

        with open(map_json_path, 'r') as f:
            data = json.load(f)

        mapsec_name = data.get('region_map_section', '')
        if not mapsec_name or mapsec_name == 'MAPSEC_NONE':
            continue

        with open(scripts_inc, 'r') as f:
            script_text = f.read()

        for match in TRAINERBATTLE_RE.finditer(script_text):
            trainer_name = match.group(1)
            if trainer_name not in trainer_to_mapsec:
                trainer_to_mapsec[trainer_name] = mapsec_name

    # Build flat array: index = trainer numeric ID, value = mapsec numeric value
    table = [mapsec_none] * trainers_count
    mapped_count = 0

    for trainer_name, mapsec_name in trainer_to_mapsec.items():
        if trainer_name in trainer_ids and mapsec_name in mapsec_values:
            idx = trainer_ids[trainer_name]
            if idx < trainers_count:
                table[idx] = mapsec_values[mapsec_name]
                mapped_count += 1

    # Generate output
    lines = []
    lines.append('/* Auto-generated by tools/generate_trainer_map_sections.py. Do not edit. */')
    lines.append('')
    lines.append('static const u8 sTrainerMapSections[%d] = {' % trainers_count)

    # Write 16 values per line for compactness
    for i in range(0, trainers_count, 16):
        chunk = table[i:i+16]
        vals = ', '.join('%3d' % v for v in chunk)
        lines.append('    %s,' % vals)

    lines.append('};')
    lines.append('')

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    print('Generated %s with %d/%d trainer mappings (%d total slots)' % (
        output_path, mapped_count, len(trainer_to_mapsec), trainers_count))


if __name__ == '__main__':
    main()
